<?php

namespace App\Modules\Chat\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Chat\Models\Chat;
use App\Modules\Chat\Models\Message;
use App\Modules\Chat\Models\MessageAttachment;
use App\Models\Tenant;
use App\Modules\Chat\Services\FileService;
use App\Modules\Chat\Services\MessageService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    public function __construct(
        protected MessageService $messageService,
        protected FileService $fileService
    ) {}

    /**
     * Store new message in chat.
     */
    public function store(Chat $chat, Request $request): JsonResponse
    {
        $request->validate([
            'content' => 'required|string',
            'type' => 'sometimes|in:text,file,system',
            'metadata' => 'sometimes|array'
        ]);

        // Check user participation
        $isParticipant = $chat->participants()->where('user_id', $request->user()->id)->exists();
        if (!$isParticipant) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $message = $this->messageService->sendMessage(
            $chat,
            $request->content,
            $request->get('type', 'text'),
            $request->get('metadata', [])
        );

        return response()->json([
            'success' => true,
            'data' => $message->load('user', 'attachments')
        ]);
    }

    /**
     * Paginate chat messages.
     */
    public function index(Chat $chat, Request $request): JsonResponse
    {
        // Check user participation
        $isParticipant = $chat->participants()->where('user_id', $request->user()->id)->exists();
        if (!$isParticipant) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $pagination = $this->messageService->paginateMessages(
            $chat,
            $request->get('cursor')
        );

        return response()->json([
            'success' => true,
            'data' => $pagination['data'],
            'next_cursor' => $pagination['next_cursor'],
            'has_more' => $pagination['has_more'],
        ]);
    }

    /**
     * Mark chat messages as read.
     */
    public function markAsRead(Chat $chat, Request $request): JsonResponse
    {
        $this->messageService->markAsRead($chat, $request->user()->id);

        return response()->json([
            'success' => true,
            'message' => 'Chat marked as read.'
        ]);
    }

    /**
     * Upload an attachment to a message.
     */
    public function uploadAttachment(Chat $chat, Request $request): JsonResponse
    {
        $request->validate([
            'file' => 'required|file|max:51200' // max 50MB
        ]);

        $file = $request->file('file');
        $tenant = $request->user()->tenant;

        if ($tenant && !$tenant->canUploadFile($file->getSize())) {
            return response()->json([
                'message' => 'Disk alanınız yetersiz. Lütfen paketinizi yükseltin.'
            ], 403);
        }

        // 1. Send placeholder message WITHOUT broadcasting
        $message = $this->messageService->sendMessage($chat, '', 'file', [], null, false);

        // 2. Upload to S3
        try {
            $this->fileService->uploadMessageAttachment($message, $request->file('file'));

            // 3. Manually broadcast with attachments loaded
            $message->load(['attachments', 'user']);
            event(new \App\Modules\Chat\Events\MessageCreated($message));

            return response()->json([
                'success' => true,
                'data' => $message
            ]);
        } catch (\Exception $e) {
            $message->delete(); // Rollback placeholder
            return response()->json(['message' => 'Upload failed: ' . $e->getMessage()], 500);
        }
    }
    /**
     * Serve an attachment via proxy to hide S3 URLs and handle private visibility.
     */
    /**
     * Serve an attachment via proxy to hide S3 URLs and handle private visibility.
     * This method is protected by 'signed' middleware but accessible without a browser session.
     */
    public function proxyAttachment(Request $request, string $id)
    {
        $attachment = MessageAttachment::findOrFail($id);

        // Security: The 'signed' middleware ensures THIS specific URL was generated by our server.
        // The URL is generated only for participants when they fetch messages.
        $message = $attachment->message;
        $chat = $message->chat;

        // Build disk manually because tenant.s3 middleware might not have run (session-less signed request)
        $disk = Tenant::getS3DiskForTenant($chat->tenant_id);

        if (!$disk) {
            abort(500, 'Storage configuration missing.');
        }

        $path = $attachment->s3_path;
        // Optional: serve preview if requested
        if ($request->has('preview') && $attachment->file_type === 'image') {
            $previewPath = str_replace('attachments/', 'attachments/previews/', $path);
            if ($disk->exists($previewPath)) {
                $path = $previewPath;
            }
        }

        if (!$disk->exists($path)) {
            abort(404, 'File not found in storage.');
        }

        $headers = [
            'Cache-Control' => 'public, max-age=604800, immutable',
            'Content-Type' => 'application/octet-stream',
        ];

        if ($request->has('download')) {
            return response()->streamDownload(function () use ($disk, $path) {
                echo $disk->get($path);
            }, $attachment->file_name, $headers);
        }

        return $disk->response($path, $attachment->file_name, $headers);
    }

    /**
     * Delete a message.
     */
    public function destroy(Chat $chat, Message $message)
    {
        // 1. Authorization: Sender OR Owner/Admin can delete
        $user = auth()->user();
        $isSender = $message->sender_id === $user->id;
        $isOwnerOrAdmin = $user->role === 'ADMIN' || 
                          $user->role === 'SUPER_ADMIN' || 
                          $chat->participants()->where('user_id', $user->id)->where('role', 'owner')->exists();

        if (!$isSender && !$isOwnerOrAdmin) {
            abort(403, 'Bu mesajı silme yetkiniz yok.');
        }

        // 2. Delete Attachments
        $fileService = app(\App\Modules\Chat\Services\FileService::class);
        foreach ($message->attachments as $attachment) {
            $fileService->deleteAttachment($attachment);
        }

        // 3. Delete Message
        $messageId = $message->id;
        $message->delete();

        // 4. Broadcast
        broadcast(new \App\Modules\Chat\Events\MessageDeleted($chat->id, $messageId))->toOthers();

        return response()->json([
            'message' => 'Message deleted successfully.',
            'message_id' => $messageId
        ]);
    }
}
